FROM oven/bun:1-alpine AS base
WORKDIR /app

COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

COPY frontend ./frontend
COPY frontend.ts ./
COPY tsconfig.json ./

EXPOSE 3002

CMD ["bun", "frontend.ts"]
